ANTISAMY_SWITCH: "false"
CANCEL_OTP_STATUS_HYSTRIX_THREAD_TIMEOUT_IN_MILLIS: "1000"
CORS_SECURITY_MAX_AGE: "380000"
DATABASE_HYSTRIX_THREAD_TIMEOUT_IN_MILLIS: "1000"
DB2_DATABASE_NAME: DMSCA00023
DB2_FUNC_PATH: SYSIBM,SYSFUN,SYSPROC,SYSIBMADM,IBM
DB2_PORT_NUMBER: "1005"
DB2_SCHEMA: ABCSchema
DB2_SERVER_NAME: server.name
DB2_USER: Reetesh
GET_STATUS_HYSTRIX_THREAD_TIMEOUT_IN_MILLIS: "1000"
PERSIST_OTP_HYSTRIX_THREAD_TIMEOUT_IN_MILLIS: "1000"
UPDATE_OTP_STATUS_HYSTRIX_THREAD_TIMEOUT_IN_MILLIS: "1000"
salt: 5000
db2DatabaseName: '{cipher}50dadd9a592774eb9470ab6412e2e0f72f5038e483ef3a3e114e6fe7457c1db7'
db2DatasourceLoginTimeout: 1000s
